// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZ6r-rtqNNQtITXxT_ymtHFXPKhAIyKQ',
    appId: '1:1088427627232:web:47b7f3bab4b4bab62ff685',
    messagingSenderId: '1088427627232',
    projectId: 'chat-app-708aa',
    authDomain: 'chat-app-708aa.firebaseapp.com',
    storageBucket: 'chat-app-708aa.appspot.com',
    measurementId: 'G-YVQQGSHE10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP143kSoLa87UTZ0N3xqOF-knGfxX25CU',
    appId: '1:1088427627232:android:4d00a7979db125302ff685',
    messagingSenderId: '1088427627232',
    projectId: 'chat-app-708aa',
    storageBucket: 'chat-app-708aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ad7EUEqd0xm4GR_olssz5XskJ5UoNzw',
    appId: '1:1088427627232:ios:345f5460db5e40092ff685',
    messagingSenderId: '1088427627232',
    projectId: 'chat-app-708aa',
    storageBucket: 'chat-app-708aa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ad7EUEqd0xm4GR_olssz5XskJ5UoNzw',
    appId: '1:1088427627232:ios:dc84bc35033cf5802ff685',
    messagingSenderId: '1088427627232',
    projectId: 'chat-app-708aa',
    storageBucket: 'chat-app-708aa.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
